package au.csiro.casda.dataaccess;

/*
 * #%L
 * CSIRO ASKAP Science Data Archive
 * %%
 * Copyright (C) 2015 Commonwealth Scientific and Industrial Research Organisation (CSIRO) ABN 41 687 119 230.
 * %%
 * Licensed under the CSIRO Open Source License Agreement (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License in the LICENSE file.
 * #L%
 */


import au.csiro.casda.datadeposit.DataDepositMessageBuilder;
import au.csiro.casda.logging.CasdaEvent;
import au.csiro.casda.logging.CasdaLogMessageBuilderFactory;

/**
 * Casda Events generated by the CasdaDataAccess application
 * 
 * Copyright 2014, CSIRO Australia All rights reserved.
 * 
 */
public enum CasdaDataAccessEvents implements CasdaEvent
{
    /**
     * Failed to process retrieve file from archive
     */
    E030("Failed to retrieve data from filesystem",
            "Unable to retrieve data for data access request. Malformed parameters. Requested %s was: %s"),
    /**
     * Not enough space in cache
     */
    E082("Failed to retrieve data for access",
            "Unable to retrieve data for data access request due to no capacity on CX_FS3. Requested %s was: %s"),
    /**
     * Invalid file request
     */
    E100("Invalid data access request",
            "Unable to retrieve data for data access request. Malformed parameters %s Reason: %s"),

    /**
     * Successful download
     */
    E134("Data retrieved", "Data retrieved successfully for fileId: %s");

    private String type;
    private String formatString;

    private CasdaDataAccessEvents(String type, String formatString)
    {
        this.type = type;
        this.formatString = formatString;
    }

    @Override
    public String getCode()
    {
        return this.name();
    }

    @Override
    public String getFormatString()
    {
        return this.formatString;
    }

    @Override
    public String getType()
    {
        return this.type;
    }

    /**
     * @return a message builder that can be used to build a message of this type
     */
    public DataDepositMessageBuilder messageBuilder()
    {
        return new DataDepositMessageBuilder(CasdaLogMessageBuilderFactory.getCasdaMessageBuilder(this));
    }
}
